### ISSUE TITLE
Inaccurate US Senators Count

### ISSUE THREAD

**Issue by siuryan** [kddove85/civicsapp#16]
In the US government tab, there's a total of 101 senators represented in the pie chart and table. This appears to be due to a GA senator stepping down from his position (Johnny Isakson), causing the table to display 3 senators for GA (the two current senators + Johnny Isakson), and the pie chart to overcount the number of Republicans by 1.

The easiest fix would be to filter out former senators so that they don't appear in the table and the pie chart.

**Comment by kddove85** [comment]
Thanks for letting me know Ryan. I looked at this a little last night and there is a field that comes back in the API request for each member called 'in_office'. The value for the field is either true or false and after investigating, Isakson's value for the field is false and the other two are true. I'll put this change in tonight. Thanks again.
